### ISSUE TITLE
setPersistenceEnabled crashing the app for some devices

### ISSUE THREAD

**Issue by savvisingh** [savvisingh/NanakShahi-Calendar#1]
`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
  at android.app.ActivityThread.access$800(ActivityThread.java:166)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5584)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
  at dalvik.system.NativeStart.main(Native Method:0)
Caused by: com.google.firebase.database.DatabaseException: 
  at com.google.firebase.database.FirebaseDatabase.zziF(Unknown Source:0)
  at com.google.firebase.database.FirebaseDatabase.setPersistenceEnabled(Unknown Source:0)
  at com.mdgiitr.nanakshahicalendar.activities.LauncherActivity.onCreate(LauncherActivity.java:54)
  at android.app.Activity.performCreate(Activity.java:5442)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)`

**Comment by savvisingh** [comment]
try this solution
https://stackoverflow.com/questions/37753991/com-google-firebase-database-databaseexception-calls-to-setpersistenceenabled

**Comment by savvisingh** [comment]
Actually I really Dont need this feature so I am gonna remove it for now, but it can be solved by adding this call to application class
