### ISSUE TITLE
Realm.getDefaultInstance()   java.lang.IllegalStateException

### ISSUE THREAD

**Issue by savvisingh** [savvisingh/NanakShahi-Calendar#2]
`java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2784)
  at android.app.ActivityThread.access$1800(ActivityThread.java:163)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5585)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.IllegalStateException: 
  at io.realm.Realm.getDefaultInstance(Realm.java:207)
  at com.mdgiitr.nanakshahicalendar.broadcast_receiver.AlarmReceiver.onReceive(AlarmReceiver.java:32)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2773)`

**Comment by savvisingh** [comment]
`try {
            realm = Realm.getDefaultInstance();
        } catch (IllegalStateException fuckYouTooAndroid) {
            Realm.init(context.getApplicationContext());
            realm = Realm.getDefaultInstance();
        }`
