### ISSUE TITLE
Android 4.4  io.realm.exceptions.RealmPrimaryKeyConstraintException:   

### ISSUE THREAD

**Issue by savvisingh** [savvisingh/NanakShahi-Calendar#4]
`io.realm.exceptions.RealmPrimaryKeyConstraintException: 
  at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:665)
  at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:450)
  at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:388)
  at io.realm.Realm.createObjectInternal(Realm.java:913)
  at io.realm.Realm.createObject(Realm.java:891)
  at com.mdgiitr.nanakshahicalendar.activities.LauncherActivity$1$1.execute(LauncherActivity.java:67)
  at io.realm.Realm.executeTransaction(Realm.java:1301)
  at com.mdgiitr.nanakshahicalendar.activities.LauncherActivity$1.onDataChange(LauncherActivity.java:64)
  at com.google.firebase.database.Query$1.onDataChange(Unknown Source:0)
  at com.google.android.gms.internal.zzbmz.zza(Unknown Source:0)
  at com.google.android.gms.internal.zzbnz.zzYj(Unknown Source:0)
  at com.google.android.gms.internal.zzboc$1.run(Unknown Source:0)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:146)
  at android.app.ActivityThread.main(ActivityThread.java:5653)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
  at dalvik.system.NativeStart.main(Native Method:0)`

**Comment by savvisingh** [comment]
Use standalone objects and then use Realm.copyToRealm() or Realm.copyToRealmOrUpdate(). This will enable Realm to check the primary value before creating any objects inside Realm.

[https://realm.io/docs/java/latest/#primary-keys](url)
